resources:
- name: pcfdemo-git
  type: git
  source:
      uri: {{github-uri}}
      branch: {{github-branch}}
- name: pcfdemo-app
  type: cf
  source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
- name: test-app
  plan:
  - get: pcfdemo-git
    trigger: true
  - put: pcfdemo-app
    params:
      manifest: cloudfoundry/manifest.yml